"""``.thm`` artifact generation for checked modules.

Scope: walking a checked module's statement list and emitting the public
theorem signatures into a sibling ``.thm`` file. Owns ``collect_public``
(the visibility walk that follows public re-exported imports through the
``collected_imports`` set) and ``print_theorems`` (the driver that writes
the artifact alongside the source).

Goes here:
  * any logic for deciding what shows up in a generated ``.thm`` file
  * the format / header / sort order of the generated file

Does NOT go here:
  * the per-statement ``print_theorems_statement`` methods themselves —
    those live on each ``Declaration`` subclass in ``declarations``
  * the consumer side (``.thm`` files are read by ``Import`` resolution
    in ``declarations``)
"""

from __future__ import annotations

from .core import *
from .terms import *
from .proofs import *
from .declarations import *
from .env import *

collected_imports: set[str] = set()

def collect_public(s: Statement, to_print: list[TheoremFilePrinting]) -> None:
    global collected_imports
    if isinstance(s, Theorem):
      if not s.isLemma:
        to_print.append(s)
    elif isinstance(s, Postulate):
      to_print.append(s)
    elif isinstance(s, Auto):
      to_print.append(s)
    elif isinstance(s, Import):
      if s.name in collected_imports:
          return
      collected_imports.add(s.name)
      if s.ast != None and s.visibility == 'public':
        for stmt in s.ast:
            collect_public(stmt, to_print)
    elif isinstance(s, Declaration) and not s.visibility == 'private':
      to_print.append(s)

def _collect_view_aliases(ast: List[Statement],
                          seen: set[str],
                          aliases: dict[str, str]) -> None:
  """Walk a module's statement list and its imports (public or
  private) and record substitutions from each non-private view's
  source-type name to the view's own name. Private imports are
  followed because views brought in through them still resolve
  Binary-style source names into this module's AST, and the ``.thm``
  display should use the view name (e.g. ``UInt``) instead of the
  private underlying type (e.g. ``Binary``)."""
  for s in ast:
    if isinstance(s, ViewDecl) and s.visibility != 'private':
      # ``source`` is declared as ``Type`` but post-uniquify it is a
      # ``VarRef`` (Term subclass). Narrow via ``cast`` so mypy doesn't
      # reject the runtime check.
      source = cast(object, s.source)
      if isinstance(source, VarRef):
        aliases[source.get_name()] = s.name
    elif isinstance(s, Import) and s.ast is not None:
      if s.name in seen:
        continue
      seen.add(s.name)
      _collect_view_aliases(s.ast, seen, aliases)

def _rewrite_var_names(node: object, aliases: dict[str, str]) -> object:
  """Return a copy of ``node`` with every ``VarRef`` whose unique name
  is in ``aliases`` rewritten to use the aliased name. Walks recursively
  via ``_map_children`` so it descends into types stored on declarations
  (RecFun, GenRecFun, …) whose ``substitute`` method is otherwise a
  no-op."""
  if isinstance(node, ResolvedVar) and node.name in aliases:
    return ResolvedVar(node.location, node.typeof, aliases[node.name])
  if isinstance(node, Var) and node.name in aliases:
    return Var(node.location, node.typeof, aliases[node.name])
  if isinstance(node, OverloadedVar):
    new_names = [aliases.get(n, n) for n in node.resolved_names]
    if new_names != node.resolved_names:
      return OverloadedVar(node.location, node.typeof, new_names)
  if isinstance(node, AST):
    return node._map_children(lambda x: cast(AST, _rewrite_var_names(x, aliases)))
  return node

def print_theorems(filename: str, ast: List[Statement]) -> None:
  global collected_imports
  collected_imports = set()
  fullpath = Path(filename)
  theorem_filename = fullpath.with_suffix('.thm')
  to_print: list[TheoremFilePrinting] = []

  for s in ast:
    collect_public(s, to_print)

  if len(to_print) == 0:
    return

  aliases: dict[str, str] = {}
  _collect_view_aliases(ast, set(), aliases)

  with open(theorem_filename, 'w', encoding='utf-8') as theorem_file:
    print('This file was automatically generated by Deduce.', file=theorem_file)
    print('This file summarizes the theorems proved in the file:\n\t' + filename, file=theorem_file)
    print('', file=theorem_file)
    for item in sorted(to_print, key=lambda s: s.key()):
      rewritten = cast(TheoremFilePrinting,
                       _rewrite_var_names(item, aliases)) if aliases else item
      rewritten.print_theorems_statement(theorem_file)
