"""``.thm`` artifact generation for checked modules.

Scope: walking a checked module's statement list and emitting the public
theorem signatures into a sibling ``.thm`` file. Owns ``collect_public``
(the visibility walk that follows public re-exported imports through the
``collected_imports`` set) and ``print_theorems`` (the driver that writes
the artifact alongside the source).

Goes here:
  * any logic for deciding what shows up in a generated ``.thm`` file
  * the format / header / sort order of the generated file

Does NOT go here:
  * the per-statement ``print_theorems_statement`` methods themselves —
    those live on each ``Declaration`` subclass in ``declarations``
  * the consumer side (``.thm`` files are read by ``Import`` resolution
    in ``declarations``)
"""

from __future__ import annotations

from .core import *
from .terms import *
from .proofs import *
from .declarations import *
from .env import *

collected_imports: set[str] = set()

def collect_public(s: Statement, to_print: list[TheoremFilePrinting]) -> None:
    global collected_imports
    if isinstance(s, Theorem):
      if not s.isLemma:
        to_print.append(s)
    elif isinstance(s, Postulate):
      to_print.append(s)
    elif isinstance(s, Auto):
      to_print.append(s)
    elif isinstance(s, Import):
      if s.name in collected_imports:
          return
      collected_imports.add(s.name)
      if s.ast != None and s.visibility == 'public':
        for stmt in s.ast:
            collect_public(stmt, to_print)
    elif isinstance(s, Declaration) and not s.visibility == 'private':
      to_print.append(s)
      
def print_theorems(filename: str, ast: List[Statement]) -> None:
  global collected_imports
  collected_imports = set()
  fullpath = Path(filename)
  theorem_filename = fullpath.with_suffix('.thm')
  to_print: list[TheoremFilePrinting] = []
  
  for s in ast:
    collect_public(s, to_print)
  
  if len(to_print) == 0:
    return
  
  with open(theorem_filename, 'w', encoding='utf-8') as theorem_file:
    print('This file was automatically generated by Deduce.', file=theorem_file)
    print('This file summarizes the theorems proved in the file:\n\t' + filename, file=theorem_file)
    print('', file=theorem_file)
    for item in sorted(to_print, key=lambda s: s.key()):
      item.print_theorems_statement(theorem_file)

